import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :nomdoc, NomdocWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Nomdoc proxy backends
config :nomdoc, NomdocProxy,
  backends: [
    %{
      # Matches www.nomdoc.com
      host: ~r/^www\.nomdoc\.com$/,
      phoenix_endpoint: NomdocWeb.Endpoint
    },
    %{
      # Matches console.nomdoc.com
      host: ~r/^console\.nomdoc\.com$/,
      phoenix_endpoint: ConsoleWeb.Endpoint
    },
    %{
      # Matches workspace.nomdoc.com
      host: ~r/^workspace\.nomdoc\.com$/,
      phoenix_endpoint: WorkspaceWeb.Endpoint
    },
    %{
      # Matches healthcare.nomdoc.com
      host: ~r/^healthcare\.nomdoc\.com$/,
      phoenix_endpoint: HealthcareWeb.Endpoint
    }
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Nomdoc.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
